name: surfpracticemagicball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.0.5 # Dart SDK version
  flutter: 3.10.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.0
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  shake: ^2.2.0
  flutter_screenutil: ^5.6.0  
  flutter_tts: ^3.7.0
  just_audio: ^0.9.34
  flutter_bloc: ^8.0.0
  file_picker: ^5.3.3
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  json_serializable:
  freezed: ^2.3.2
  flutter_lints: ^2.0.1
flutter:
  
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/